use qalert_bd; 
 
 
 INSERT INTO endpoint(endpoint_name,method,description)
 VALUES 
 ('/user','POST','Registra un nuevo usuario'),
 ('/security/login','POST','Inicio de sesión'),
 ('/security/get-verification-code','POST','Código de verificación para iniciar sesión en otro móvil'),
 ('/qalert','POST','Actualiza la suscripción de un usuario'),
 ('/suggestions','POST','El usuario comenta una sugerencia'),
 ('/profile','POST','Registra un nuevo perfil al usuario'),
 ('/profile','PUT','Modifica el perfil del usuario'),
 ('/profile/fetch-by-user-id','GET','Listado de perfiles'),
 ('/profile','DELETE','Elimina el perfil del usuario'),
 ('/master/get-terms-and-conditions','GET','Muestra los términos y condiciones al usuario'),
 ('/master/get-app-settings','GET','Ajustes de Configuración'),
 ('/scan/get-additives-from-image','POST','Detecta aditivos desde un texto y devuelve su reporte de toxicidad'),
 ('/scan','POST','Guarda el resultado final del escaneo del producto'),
 ('/scan/get-additives-report','POST','Obtiene el reporte de toxicidad del producto escaneado'),
 ('/scan/get-scan-list','GET','Listado de escaneos del usuario en los últimos 30 días'),
 ('/additive','GET','Lista todos los aditivos registrados'),
 ('/aliment','GET','Listado de alimentos'),
 ('/user/update-password','PUT','Actualiza la contraseña del usuario'),
 ('/payment', 'POST', 'inserta un nuevo pago en el sistema y genera url de izipay'),
 ('/subscription','GET','Obtiene el listado de suscripciones activas del sistema'),
 ('/payment/update','POST','actualiza el estado de un pago en el sistema'),
 ('/user/existing-user','POST','verifica si el usuario ingresado existe en el sistema'),
 ('/payment','GET','Obtiene los datos de un pago');

-- ***********************************************************************
-- ********************************************************************DML
-- ***********************************************************************
insert into master(table_id, field_id, description, status)
values(1, 0, 'App settings', 0);

insert into master(table_id, field_id, description, value_varchar)
values(1, 1, 'Terms and conditions', 'What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.');

insert into master(table_id, field_id, description, value_int)
values(0, 0, 'Services settings', null)
	,(0, 1, 'Verification code expiration time in minutes.', 10);
    
insert into status_type(status_type_id, name)
values(1, 'General')
	, (2, 'User and person')
    , (3, 'Profile')
    , (4, 'Additive');

insert into status(status_id, status_type_id,status_code, name)
values(1, 1,'ACTIVE_GE','Active')
	, (2, 2,'ACTIVE_US_PERSON','Active')
    , (3, 3,'ACTIVE_PF','Active')
    , (4, 4,'ACTIVE_ADDV','Active');

insert into document_type(document_type_id, name)
values(1, 'DNI')
	, (2, 'Carnet de extranjería')
	, (3, 'Cédula de identidad');

insert into toxicity_level(name, level, color)
values('Inofensivo', 1, '#00913f')
	, ('Medio', 2, '#FFFF00')
    , ('Nocivo', 3, '#ff0000');


insert into status(status_type_id,status_code,name,status)
values(3,'INACTIVE_PF',"inactive",0);


insert into master(table_id,field_id,sequence,created_datetime,status,description,value_int,value_varchar)
value(0,2,1,now(),1,"Máximo perfiles para no premium",1,"1 adicional");

insert into master(table_id,field_id,sequence,created_datetime,status,description,value_int,value_varchar)
value(0,3,2,now(),1,"Máximo perfiles para premium",4,"3 adicionales");

INSERT INTO suggestions_type (description) VALUES 
  ('Muy Enojado'),
  ('Enojado'),
  ('Indiferente'),
  ('Satisfecho'),
  ('Encantado');

INSERT INTO master(table_id,field_id,description,value_int) VALUE(1,2,'Indicador de días para la actualización de la tabla de alimentos de la bd local del dispositivo',7);


insert into additive_function(additive_function_id, additive_function_name) values(1,'ACIDULANTE');
insert into additive_function(additive_function_id, additive_function_name) values(2,'AGENTES DE TRATAMIENTO DE LAS HARINAS');
insert into additive_function(additive_function_id, additive_function_name) values(3,'ANTIAGLOMERANTE');
insert into additive_function(additive_function_id, additive_function_name) values(4,'ANTIAGLUTINANTE');
insert into additive_function(additive_function_id, additive_function_name) values(5,'ANTIESPUMANTE');
insert into additive_function(additive_function_id, additive_function_name) values(6,'ANTIOXIDANTE');
insert into additive_function(additive_function_id, additive_function_name) values(7,'CLARIFICANTE');
insert into additive_function(additive_function_id, additive_function_name) values(8,'COLORANTE');
insert into additive_function(additive_function_id, additive_function_name) values(9,'CONSERVANTE');
insert into additive_function(additive_function_id, additive_function_name) values(10,'DISOLVENTE');
insert into additive_function(additive_function_id, additive_function_name) values(11,'EDULCORANTE');
insert into additive_function(additive_function_id, additive_function_name) values(12,'EMULSIONANTE');
insert into additive_function(additive_function_id, additive_function_name) values(13,'ENZIMA');
insert into additive_function(additive_function_id, additive_function_name) values(14,'ESPESANTE');
insert into additive_function(additive_function_id, additive_function_name) values(15,'ESPUMANTE');
insert into additive_function(additive_function_id, additive_function_name) values(16,'ESTABILIZADOR');
insert into additive_function(additive_function_id, additive_function_name) values(17,'GASES');
insert into additive_function(additive_function_id, additive_function_name) values(18,'GASIFICANTE');
insert into additive_function(additive_function_id, additive_function_name) values(19,'OXIDANTE');
insert into additive_function(additive_function_id, additive_function_name) values(20,'POTENCIADOR');
insert into additive_function(additive_function_id, additive_function_name) values(21,'REVESTIMIENTO');



insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(1,'Fruta','g_frutas.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(2,'Aceite ','g_aceites.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(3,'Verdura','g_verduras.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(4,'Planta / Hierba ','g_plantas.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(5,'Semilla','g_semillas.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(6,'Legumbre','g_legumbres.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(7,'Fruto seco','g_frutossecos.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(8,'Cereal','g_cereales.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(9,'Especia','g_especias.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(10,'Fruto','g_fruto.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(11,'Tubérculo','g_tuberculos.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(12,'Hongos','g_hongos.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(13,'Hierba','g_hierbas.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(14,'Alimento vegetal','g_vegetales.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(15,'Lácteo','g_lacteos.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(16,'Bebida vegetal','g_bebidas.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(17,'Maíz','g_maiz.png');
insert into aliment_category(aliment_category_id, aliment_category_name, image_name) values(18,'Condimento','g_condimentos.png');



insert into aliment(aliment_name,letter,description,aliment_category_id)values('Albaricoque','A','Abundante en las tres vitaminas antioxidantes (A, C y E) siendo un buen aliado para prevenir la degeneración celular. Es rico en glúcidos (fructosa y glucosa). Su riqueza en betacaroteno contribuye a la salud de los ojos y de la piel, así como a la resistencia ante las infecciones.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aceite de oliva','A','Rico en ácidos grasos, principalmente ácido oleico. Reduce el colesterol malo y los triglicéridos. Incrementa el colesterol bueno. Contiene antioxidantes y vitamina E. Es bueno para el corazón, la piel, los huesos, protege el estómago, combate el estreñimiento y el organismo en general.',2); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aceite de coco (Virgen)','A','Excelente para elaborar postres saludables. Posee propiedades antivirales y antimicrobianas. Ayuda a combatir la bacteria Helicobacter pylori relacionada con las gastritis, las úlceras y el cáncer de estómago. Pueden mejorar los niveles de colesterol. Es grasa saludable siempre y cuando sea "Aceite de coco virgen".',2); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aceituna','A','Rico en ácido oleico y aceites esenciales como el Omega 3 y 6. Aporta fibra, hierro y cantidades considerables de sustancias polifenoles antioxidantes y antiinflamatorias. Estimula la producción de endógenos. Anticancerígena, protege la piel, los huesos y el corazón.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Acelga','A','Excelente fuente de calcio, potasio, hierro y magnesio. Tiene pocas calorías, pocas grasas, es alto en fibra y antioxidantes. Contiene vitaminas C, E, A, B1 y B2. Posee provitamina A (betacaroteno) y ácido fólico. Refuerza los huesos, ayuda a adelgazar, combate el estreñimiento y la anemia.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Achicoria','A','Posee propiedades depurativas y diuréticas. Rica en vitaminas A y B. Minerales: potasio, calcio, magnesio y fósforo. Contiene ácido fólico, ácido pantoténico, niacina y riboflavina. Alto en antioxidantes. Bueno para el colesterol, problemas digestivos, riñones, sistema inmune. Anticancerígeno y alivia el estrés.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aguacate (Palta)','A','Tiene potasio, fuente de energía y de grasas saludables. Su contenido en magnesio favorece al funcionamiento del sistema nervioso y muscular. Regula los niveles de glucosa en la sangre. Da soporte al sistema inmunológico. Tiene ácido fólico. El omega 3 de la palta cuida el sistema cardiovascular.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aguaymanto','A','Abundante en vitaminas A, B y C, así como de hierro, fósforo y carbohidratos. De propiedades antioxidantes. Bajo en calorías. Combate asma y sinusitis. Mejora el desempeño cardiovascular. Ayuda a estabilizar el nivel de glucosa en la sangre. Desinflama las articulaciones.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ajo','A','Contiene pocas calorías, pero es muy rico en vitamina C, vitamina B6 y manganeso. Además, posee fructosanas y enzimas. Provee varios minerales, incluidos el fósforo, calcio, potasio, hierro, selenio y cobre. Reduce el colesterol, es depurativo, antiséptico y antibacteriano.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ajonjolí','A','Son ricas en ácidos grasos esenciales Omega 3 y Omega 6. Son fuente de fibra que ayuda a mejorar el tránsito intestinal y a reducir la absorción del colesterol. Posee vitaminas E, B1, B3, B6 y ácido fólico, y minerales como el hierro, fósforo, magnesio, calcio, potasio y zinc.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Albahaca','A','Contiene un aceite esencial rico en estragol, cineol y eugenol, flavonoides y saponósidos. Favorece la digestión, disminuye flatulencias y la pesadez abdominal. Es diurético, suaviza la garganta, contribuye a calmar las jaquecas (de origen digestivo o hepático) y dolores menstruales.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Alcachofa','A','Rico en calcio, fósforo, magnesio, potasio, fibra y vitaminas del grupo B –B1, B6 y ácido fólico. Protege el hígado. Contiene inulina, fácil de asimilar por los diabéticos. Es un alimento depurativo que mejora además las digestiones lentas. Incrementa la diuresis y la excreción de urea.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Alfalfa','A','Contiene vitaminas del grupo B, vitaminas C, D, E, K y P. Minerales como el calcio, hierro, fósforo y potasio. Es antibacteriana, antioxidante y antiinflamatoria gracias a su contenido en flavonoides y fitoesteroles. Fuente de proteínas vegetales. Combate la anemia, trata el hipotiroidismo y mejora la artrosis.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Algarroba','A','Ricas en calcio, hierro y vitaminas B2 y B6. Aporta proteínas ricas en triptófano y abundantes azúcares (reduce la necesidad de usar otros endulzantes). Tiene fibra y taninos que favorecen la salud intestinal y la inflamación. Al mismo tiempo la hacen útil frente al colesterol.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Algas','A','Alto contenido de yodo. Son buena fuente de fósforo y calcio. Presencia de vitamina A, B, C y D. Poseen minerales como el potasio y pequeñas dosis de selenio y zinc. En las algas las fibras forman mucílagos, polisacáridos que retienen varias veces su volumen en agua.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Almendras','A','Son ricas en fibras, proteínas, vitaminas B y E, grasas saludables monoinsaturadas, hierro, calcio, fósforo, magnesio y manganeso. Antioxidante, antiflamatorio, controla el peso, vigoriza y es cardiosaludable.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Aloe Vera','A','Fuente de vitaminas, minerales, enzimas, aminoácidos, ácidos grasos y agua. Contiene antraquinones. Desintoxicante, digestivo, depurativo, regenerador celular, bactericida, antiséptico, antiinflamatorio, analgésico, antiviral, inhibidor del dolor, anti-coagulante, estimulador del sistema inmune.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Amaranto','A','Contiene todos los aminoácidos esenciales. Vitaminas A, B1, B2, B3, C y ácido fólico y minerales como calcio, hierro, magnesio y potasio. También destaca por su contenido en omega 6, omega 3 y omega 9, Alto contenido en fibra. No tiene gluten. Tiene un perfil nutricional muy completo.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Anís','A','Aporta vitaminas A, C y del grupo B, que benefician nuestros ojos y aseguran la retención del hierro. Contiene calcio, fósforo, zinc, magnesio y potasio, minerales que mejoran el rendimiento muscular y refuerzan los huesos. Es digestivo, diurético, expectorante, analgésico y antimicrobiano.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Apio','A','Contiene aceites esenciales de limoneno o selineno que le brindan alto poder depurativo y diurético. Sus hojas son una fuente rica de antioxidantes flavonoides.  Además, es rico en ácido fólico, riboflavina, niacina y vitamina C, que son esenciales para el metabolismo óptimo del organismo.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Arándanos','A','Muy rico en antioxidantes. Posee resveratrol, conocido por su efecto anticancerígeno. Tiene minerales esenciales como el manganeso, vitamina C y varias vitaminas del grupo B. Es antioxidante y antiinflamatorio, previene infecciones urinarias y digestivas. Controla la hipertensión.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Arroz integral','A','Excelente fuente de energía gracias a su riqueza en hidratos de carbono, entre ellos el más abundante es el almidón, que le otorga al organismo energía gradual. Tiene proteínas, con una cantidad considerable de triptófano y lisina. Tiene fibra, magnesio y ácido fólico. No contiene gluten.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Arvejas','A','Ricos en proteínas. Además de una fuente de fibra que ayuda a regular el tránsito intestinal y estreñimiento. También es rico en potasio, indispensable para el buen funcionamiento del sistema nervioso. Contiene ácido fólico, y vitaminas que favorecen la creación de células sanguíneas.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Avellana','A','Son ricas en ácido oleico, antioxidantes (destacando la vitamina E) así como en fitonutrientes. Fuente de minerales como calcio, fósforo y magnesio, indispensables para el crecimiento, así como de manganeso. Protege el corazón, combate el estreñimiento y equilibra el sistema nervioso.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Avena','A','Contiene una fibra soluble llamada betaglucano. Alto en fibra y proteínas. Rica en minerales como magnesio, hierro, manganeso y vitamina B1. Así como numerosos antioxidantes y antiinflamatorios. Controla el azúcar, baja el colesterol, es digestiva y equilibra el sistema nervioso.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Azafran','A','Tiene crocina, antioxidante natural que elimina los radicales libres, responsables de causar el envejecimiento de las células. Bueno para la visión, gracias al safranal que mejora las funciones de la retina. Posee crocetina que ayuda a reducir el colesterol. Bueno para la memoria.',9); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Berenjena','B','El 92% de su peso es agua. Es un buen antioxidante y también aporta fibra. En cuanto a sus micronutrientes, destaca principalmente su aporte en potasio y ácido fólico. Es digestiva, diurética, controla el colesterol y el azúcar. Es buena para el sistema nervioso. Protege el hígado.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Berro','B','Alto contenido de calcio y fósforo que ayuda a mantener huesos y dientes sanos. Combate la anemia gracias a su contenido en hierro. Mantiene en buen estado el sistema nervioso a través del potasio. Es antioxidante. Posee betacaroteno que limpia y cuida la piel. Contiene ácido fólico.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Borraja','B','Su contenido en hierro es importante y ayuda a prevenir problemas de anemia. Asimismo, también es rica en potasio, que regula la actividad del sistema nervioso. También ayuda a regenerar tejidos y prevenir la actuación de los radicales libres a través de las vitaminas A y C.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Brócoli','B','Alto contenido en hierro, clorofila y ácido fólico. Ayuda a eliminar el colesterol malo. Desintoxica el organismo. Contenido notable de calcio, fósforo, magnesio y zinc. Cuida la salud ocular gracias a la zeaxantina, el betacaroteno, y la vitamina A. Contiene fibra. Es anticancerígeno.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cacahuate','C','Es una legumbre más no un fruto seco. Alimento importante en el Perú de los incas. Tiene una gran fuente de proteínas, hierro, ácido fólico, fibra, etc. Controla las tasas de colesterol, mejora el sistema inmune, mejora el ánimo y sueño. No cambia el sabor con comidas.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cacao','C','Capricho energético y bueno si se consume moderadamente. Tiene antioxidantes y antidepresivos. Aporta vitamina E y varias del grupo B. Aliado de nuestro corazón, puesto que incrementa el “colesterol bueno”. Amigo de nuestro cerebro ya que evita la acumulación de una proteína para evitar el Alzheimer.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Calabaza','C','Alimento excepcional con mala fama por las historias. Aporta betacaroteno, Vitamina C y E y las B. Su riqueza en Zinc la hace distinta de muchas. Ayudante de nuestros niños para su aprendizaje. Muy recomendable en el embarazo. Se puede preparar en un sin fin de platillos culinarios.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Camote o Boniato','C','Es rico en provitamina A, en forma de betacaroteno. Es esencial para la piel, la salud visual y el desarrollo óseo. Contiene fibra. Es una gran fuente de magnesio, entre otros minerales como el manganeso, potasio, cobre y hierro. Tiene vitaminas C, B6, B5, B1 y B2. Es antioxidante.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Camu camu','C','Fruta con 40 veces más vitamina C que el limón. Posee distintos compuestos bioactivos que sirven para prevenir el cáncer y enfermedades cardiovasculares. Con aminoácidos importantes como serina, valina y leucina. Favorece a la restructuración de cartílagos, ligamentos y colágeno.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Canela','C','Se sugiere consumir en pocas cantidades, ya que no aporta nutrientes tan importantes. Contiene componentes con gran poder antinflamatorio y antioxidante. Se emplea para tratar problemas respiratorios, ginecológicos y digestivos. Ayuda en la pérdida de peso, y en trastornos nerviosos.',9); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Canónigos','C','Planta que alegra el corazón e iluminan las ensaladas. ‘’Hierba de los gatos’’ por que ayuda a que se purguen. Cuenta con hierro, vitamina C ,E y potente en vitamina A. Así mismo nos ayuda fortaleciendo el cabello y uñas. Útil para la anemia. También se usa en platillos calientes.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cáñamo','C','Hierba anual asiática, de fibra fuerte y dúctil que se obtiene de ella. Es una planta dioica (o sea que una planta tiene flores masculinas y otra las femeninas), llamados hermafroditas, entre las que podemos citar las de procedencia thailandesa, perteneciente a la clase de las dicotiledóneas.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cañihua','C','Se caracteriza por su alto contenido en proteínas y fibra. Posee capacidades antioxidantes por sus fenólicos. Aumenta la masa muscular. Además, la harina de Cañihua es libre de gluten, por lo que puede usarse en dietas para celiacos. Puede acompañarse con cualquier alimento.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Caqui','C','“Fruta del fuego Divino”, más de mil variedades, pero comercialmente se dividen en: Si/No astringentes. Con fructosa y glucosa que ayuda a la energía. Alivian la gastritis y tránsito intestinal. Amigo anti estrés y de nuestra vista. Se consume maduro como fruta y algunos platillos como pizza.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Carambola','C','Fruta estrella tropical para cualquier momento. Es baja en calorías, contiene mucha agua y es baja en grasas lo que la hace ayuda con la pérdida de peso. Contiene Potasio, Vitamina C, etc. Se recomienda evitarlas para personas con cálculos renales. Rinde mucho para jugo y refrescos.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Castaña','C','Fuente inagotable de energía de calidad. Fruto seco o cereal. Aumenta el nivel de glucosa, perfecto coach de deportistas. Ayuda a diabéticos en cantidades moderadas. Rico en antioxidantes. Para que no resulten pesadas se sugiere cocinarlas con conocimiento previo y con anises, jengibre, etc.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cebada','C','“Ofrenda de los dioses” por su línea histórica. Es remineralizante por el potasio, calcio, etc. Rica en vitaminas del grupo B y betaglucanos que mejoran el sistema inmune. Controla el colesterol y protege nuestro corazón. En la cocina tiene muchos usos, incluso reemplaza el arroz o papillas.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cebolla','C','Gran medicamento natural. Desde diurético, curas heridas y trata neumonías. Recomendado para enfermedades respiratorias. Rica en fibra, carbohidratos, etc. Alto porcentaje del oligoelementos y antioxidantes que protegen del cáncer y distintas alergias. Protagonista infaltable en nuestra cocina.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Centeno','C','Uno de los cereales más similares al trigo. 100gr de pan de este cubre el 18% de lo necesario en hierro, fósforo al día y varias del grupo de vitamina Abundante en fibra que ayuda a la digestión. Bueno para la diabetes e hipertensión. Contiene gluten, pero en niveles bajos.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cereza','C','“Fruta bella en estado puro”. Aunque sea bajo en grasas y proteínas, es abundante en hidratos de carbono y fructosa. Destaca en potasio, vitamina C, antocianinas, etc. Aliada de nuestra piel y huesos que lo hace antiedad. Con multiusos, desde ensaladas, postres, heladas hasta sopas.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Champiñón','C','Una de las setas más conocidas y comercializadas en España y Europa. Su riqueza se presenta en las vitaminas del grupo B (1,2,3) y ácido fólico que cubren las necesidades diarias aumentando las defensas del cuerpo. Previene el cáncer y se usa en un sinfín de platillos de comida.',12); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Chia','C','“Fuerza” en dialecto maya. Fuente inagotable de fibra antioxidantes, calcio, proteínas y omega 3 de origen vegetal. Aliado de los diabéticos regulando el azúcar en la sangre. Ayuda con la pérdida de peso. Mayormente se combina con distintas ensaladas, yogurt, jugos para iniciar el día.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Chirimoya','C','“Semillas Frías”, posiblemente los mochicas la probaron por primera vez en la historia. Brinda glucosa, fructosa y calorías que llenan de energía. Regula la tensión arterial, fortalece el cuerpo. Un gran colega para combatir la anemia. Fruta refrescante y buen acompañante.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cilantro','C','Planta comestible y usada en los platillos de cocina. Su aceite es esencial para la secreción gástrica. Cuenta con propiedades como carminativo, estrogénico y espasmolítico, etc. Se utiliza para combatir la pérdida de apetito, hemorroides vértigo, vómitos. Evitar durante el embarazo.',13); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ciruela','C','Fruta apetecible en primavera. Abundante en agua, aporta potasio, calcio, magnesio y hierro. Contiene cantidades notables de Vitamina C, E, etc. Siendo así un alimento energético y alcalinizante. Al tener bajo contenido calórico es bueno para el sobrepeso. Alivia la retención de líquidos.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Clavo de olor','C','Es una de las hierbas protagonistas de muchas cocinas. Es conocía por su efecto aromático. Cuenta con propiedades anestésicas, analgésicas, actibacteriales y estimulantes afrodisíacas por su contenido en eugenol. Disminuye los niveles de glucosa en la sangre. Con vitamina K y omega 3.',9); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Coco','C','Creación maravillosa de la naturaleza. Es calórico ya que 100gr nos brinda 342 calorías, aunque notable en fibra. Su harina es de cero gluten y el doble de proteínas. La leche no se queda atrás por sus propiedades, aunque se debe regular su uso para personas que buscan adelgazar.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cocona','C','Fruta nutritiva amazónica. Regula el colesterol, la diabetes y excesos de ácido úrico. Así mismo, ayuda con las enfermedades de los riñones e hígado. Alto en agua aprovechable para refrescos. Aliado de nuestro cabello mejorando su apariencia. Regula el nivel de azúcar en la sangre.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cola de Cabello','C','Esta es una de las plantas silvestres más primitivas, alcanzaban un enorme tamaño.Es una de las hierbas medicinales más consumidas en el mundo, tiene muchas propiedades terapéuticas y estéticas, pero principalmente se le conoce por sus propiedades regenerativas, por sus efectos depurativos, de grandes efectos para la belleza y la salud de la piel.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Coles','C','El invierno debe oler a coles. Se dice que estos vegetales han conquistado el mundo. Aunque no parezca es fuente importante de vitamina C, siempre y cuando se consuman crudas o ligeramente cocidas. También cuenta con selenio y varios flavonoides en dosis importantes. Protege del cáncer.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Culantro','C','Esta planta forma parte de los remedios tradicionales herbolarios contra afecciones respiratorias- como el asma- y estomacales. Para las comunidades amazónicas, el culantro puede poseer propiedades antinflamatorias y analgésicas. Por su parte, la ciencia comprueba que contiene altas cantidades de calcio, hierro, vitamina A, B2, B1 y C.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cúrcuma','C','Símbolo de prosperidad en la India. Esta planta contiene un aceite esencial con zingibereno, polisacáridos y sales minerales importantes. Un antioxidante que también ayuda contra la artritis, así mismo mejora la circulación y combate enfermedades neurodegenerativas como el Alzheimer.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Cushuro','C','Posee una alta concentración de proteínas, superando a la carne y el pescado. Contiene calcio, hierro, potasio y sodio, así como vitaminas B1, B2, B5 y B8 que fortalecen nuestro sistema inmune y optimizan el funcionamiento de nuestro sistema óseo, nervioso, cardiovascular y digestivo',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Dátil','D','Al parecer su árbol fue el primero que cultivó el hombre. Presenta elevado porcentaje de nutrientes y calorías. Con vitamina B5 que ayuda a convertir las grasas y carbohidratos en energía. Aliado físico y mental. Alto en potasio y ayuda a conciliar el sueño. Ablanda las vías respiratorias.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Diente de León','D','Esta hierba contiene eudesmanólido(tarascona), germagranólidos, triterpenos y esteroles. Tiene vitamina B y C. Aliado contra las hemorroides, gota, reumatismo, afecciones de la piel, etc. Puede producir dermatitis e hiperacidez gástrica y precaución de uso quienes tengan hipertensión.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Durián','D','Esta planta exótica es hallada principalmente en el sudeste asiático, los frutos que produce tienen un peso aproximado de cinco kg, la principal característica es el olor o el mal olor que desprende cuando esta maduro, llegando a ser repugnante en ocasiones. Sucediendo todo lo contrario con el sabor, pues se le considera el rey de las frutas.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Eleuterococo','E','También conocido como Ginseng siberiano. Posee propiedades antiinflamatorias y vasoprotectoras. Recetado para estrés, fatiga, convalecencia, hipotensión, etc. Perfecto coach de deportistas y mejora la concentración en estudiantes. Regular su uso si hay efectos secundarios fuertes.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Escarola, endivia y achicoria','E','Son hortalizas nutritivas, sabrosas, saludables y depurativas. Ofrecen color a los platos de invierno, especialmente a las ensaladas. Ricas en carbohidratos, fibra y baja en calorías. Tiene vitamina A. La achicoria aumenta la producción de bilis para mejorar la dermis y ayuda a diabéticos.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Espárrago','E','Perú es primer país exportador mundial. Debido a su ácido fólico, vitamina B9 y K. El verde tiene un sabor más fuerte y textura más dura a comparación del blanco. Alto en fibra y ayuda a prevenir el cáncer de colon y otros. Retrasa el proceso de envejecimiento y deterioro del cerebro.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Espinaca','E','Inseparable de Popeye. Alto en vitaminas y minerales. Contiene clorofila, enzimas y rica en fibra. Se recomienda evitar con personas propensas a cálculos. Enemigo de la Anemia y del colesterol. Resulta ideal en las ensaladas durante el embarazo. Desde tortillas, cremas, sopas en la cocina.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Estevia','E','Edulcorante por excelencia siendo 300 veces más dulce que la sacarosa. Fiel acompañante de los diabéticos, así mismo es laxante osmótico. Contiene aceites volátiles como nerolidol y carvofileno. También es muy buena para los problemas de depresión y sirve como antibacteriano.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Eucalipto','E','Tiene un efecto antibacteriano y fungicida. Es un expectorante por excelencia y disminuye las secreciones cuando se usa de forma tópica.  Combate enfermedades como la sinusitis, asma, fiebre, gripe, incluso trastornos gástricos, etc. Sin embargo, hay que ser precavido sin llegar a sobredosis.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Frambuesa','F','Dulces, jugosas y muy beneficiosas para la salud. Una de las frutas menos calóricas y rica en agua. Cuenta con manganeso,ácidos orgánicos,etc. Evita la fatiga, es desintoxicante y estimula el apetito. También se puede usar sus hojas para infusiones aliviando dolores menstruales, etc.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Fresa','F','Alegran la vista y el paladar. Con notable riqueza mineral en especial el hierro. Muy usado para tratamientos de déficits nutricionales. Ayuda contra la gota, reumatismo y artritis gracias a su alcalinización. Fiel snack de embarazadas y niños. Evitar en caso de intestino delicado, etc.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Frijol','F','Sus carbohidratos absorben más lentamente que los simples (azúcar, dulces, mieles, confites, etc.), por lo tanto ayudan a prevenir aumentos abruptos en los niveles sanguíneos de azúcar. Tienen un bajo contenido de grasa y, por lo tanto,  no contienen colesterol.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Garbanzo','G','Especie leguminosa muy apreciada. Fuente destacable en hidratos de carbono de absorción lenta. Rico en fibra, muy proteico y pobre en grasas saturadas. Mejora la fatiga y personas con esfuerzos físicos constantes. Regula la tensión arterial. Ácido fólico notable para embarazadas.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Genciana','G','Es una planta perenne. Cuenta con sustancias amargas que estimulan la secreción de saliva y jugos gástricos. Se considera como tónico o estimulante. Se utiliza con alteraciones digestivas, en anorexia, disminuye la flatulencia. Previene la gripe por el efecto antipirético. Ayuda con las úlceras.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Germinados','G','Semillas que son pequeño tesoro para el organismo. Al remojarlas la cáscara se ablanda y se abre activando sus enzimas y asimilando más beneficios. Regenera la flora intestinal, estimulan los jugos pancreáticos. Potencian la producción de leche materna y regulan el Sistema Endocrino.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ginkgo Biloba','G','Planta medicinal que mejora el flujo sanguíneo y protege el sistema nervioso, mejorando la memoria y previene la demencia senil. Ayuda contra la enfermedad oclusiva periférica arterial. Sirve como diurético, sin embargo, se advierte en su uso con personas hipertensas o diabetes senil. Como té o extracto se suele usar.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ginseng','G','Planta medicinal con sustancias como ginsenósidos. Revitalizador para el cansancio y el estrés. Aliado íntimo y sexual para aumentar el placer en parejas. Estimula el cerebro y mejora las actividades cognitivas. Previene la gripe y lo más importante el cáncer. Consumir en sopa,té cápsulas,etc.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Gírgola','G','También conocida como seta de ostra, champiñón ostra o pleuroto. Alto en fibras ayudando a limpiar los intestinos.  Reduce el colesterol LDL en la sangre. Vitaminas B, D, C, y K, ácidos grasos insaturados (omega 3,6,7,9), fortalece el sistema inmunológico.',12); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Girasol','G','Las semillas de esta lúcida planta se indica como lubricante contra el estreñimiento y usarlo como emoliente por su valor nutritivo. Confieren propiedades antiateromatosas e hipolipemiantes disminuyendo los niveles de lípidos en sangre y aliado contra el colesterol mejorando nuestra circulación.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Granada','G','Fruta afrodisiaca de los tiempos remotos. Rica en fotoquímicos como flavonoides, antocianinas y elagitaninos. El zumo de esta contiene antioxidantes tanto como el té verde. Enemigo clave de todo tipo de cáncer. Es ligera, digestiva y depurativa, básica para dietas de adelgazamiento.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Granadilla','G','Esta fruta posee propiedades antioxidantes y abundante en vitaminas y minerales. Se recomienda para tratar el insomnio y la ansiedad. Su eficacia en los síntomas neurológicos y los sofocos asociados con la menopausia lo hacen un gran aliado. Desde mermeladas, helados, yogurt hasta jugos.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Granola (Muesli)','G','“Papilla de cereales”. Esta nutritiva combinación de cereales integrales, frutas secas, entre otros, aporta energía y fibra insoluble. Fortalece el corazón y sistema nervioso. Aliado de diabéticos y de gente adulta y mayor. Puede colocarse desde una ensalada de frutas, yogurt o postres.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Grelo','G','Procedentes del nabo. Abundantes en agua y fibra. Fuente de vitamina B9 necesaria para la buena renovación de glóbulos rojos y prevención de anemia. Así mismo aporta la misma cantidad de vitamina E que el brécol o leche de soja. Recomendado durante el embarazo para el desarrollo del bebe.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Guanábana','G','Rica en vitaminas C, B1 Y B2 que fortalecen el organismo. Es poderosa contra la hipertensión, inflamaciones por sus propiedades hepatoprotectoras, etc. Alta en fibra y ayuda a convertir los carbohidratos en energía. También ayuda al crecimiento y producción de glóbulos rojos. Se puede hacer hasta en harina.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Guaraná','G','Es una pasta seca hecha de las semillas de P. cupana. Desde jarabes, extractos y destilados utilizados como saborizantes y fuente de cafeína en refrescos. Considerado afrodisíaco. Ayuda a reducir el peso. Está contraindicado en el embarazo y lactancia. Puede producir insomnio.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Guayaba','G','Es una fruta aromática con sutil dulce o ácido según la variedad. Su riqueza en vitamina C es excepcional y altos en betacaroteno. Su contenido astringente la hacen eficaz contra las diarreas. Se come con o sin cáscara y sin pepitas. Su pectina la hace ideal para hacer mermeladas, etc.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Habas','H','Son legumbres ricas en proteínas y fibra. Idóneas en guisos, cremas, con jamón o hasta revuelta con huevo. De carne tierna y sabrosa. El ser altas en hierro lo hacen un alimento contra la anemia. Regula el tránsito intestinal y estreñimiento Así mismo reduce el colesterol y problemas cardiovasculares.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Hamamelis','H','Las hojas de esta planta se indican para trastornos de varices, hemorroides y flebitis y aliado de la mujer contra la menopausia. Buen cicatrizante en heridas y en algunas dermatitis al ser antibacteriano. Buen antinflamatorio en forma de compresas. Ayuda en colirios para ojos irritados.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Hierba buena','H','Planta medicinal y aromática que ayuda a reducir trastornos digestivos como gases, hinchazón, náuseas, indigestión o cólicos. También es efectiva para aliviar los síntomas del intestino irritable. relajación de los músculos lisos en el tracto digestivo. Mejora el mal aliento.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Higo','H','Una fruta única de piel suave, pulpa melosa. A pesar de ser muy dulce no tiene tantas calorías y es un poco mayor al de las manzanas.  Ricos en potasio, calcio, hierro, etc. Mantiene en buen estado el sistema nervioso y músculo esquelético. Bueno para nuestra piel por el psoraleno.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Hinojos','H','El fruto se indica en tisanas contra el estreñimiento, favorece la lactancia materna, ayuda contra enfermedades urinarias y en la inapetencia. Así mismo en la bronquitis y espasmos.  Se utiliza también en gárgaras y baños oculares. Evitar uso excesivo que podría ser neurotóxico. Perfecta para hacer infusión.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Hongo negro','H','Contiene sustancias anticoagulantes y ayuda a mejorar la circulación. Puede reducir el colesterol y el azúcar en la sangre.',12); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Holantao (Colantao)','H','Más conocido como arveja china, usándose en platillos de chifas. Se trata de una vaina o fruto inmaduro. Rica en vitamina A y en fibra. A pesar de no poseer muchos nutrientes es alto en la concentración de vitamina C, a comparación de la arveja tradicional tiene menos contenido calórico.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Humus','H','Alto contenido en hierro y fibra. Es un alimento muy beneficioso en situaciones de estrés, irritabilidad, nerviosismo y falta de sueño. un alimento muy beneficioso en situaciones de estrés, irritabilidad, nerviosismo y falta de sueño.',14); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Jengibre','J','Una planta con sustancias fenólicas y abundantes vitaminas y minerales. Combate los mareos y náuseas ayudando a las embarazadas. Un pequeño trozo de este encurtido con vinagre ayuda contra el mal aliento refrescando la boca. Ayuda contra resfriados, es bueno en sopas y anticancerígeno.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Jojoba','J','Planta medicinal proveniente del Norte de México y Sur de Estados Unidos. Alto en Vitamina E, por su contenido de antioxidantes ayuda a fortalecer el cabello, las uñas, la piel y previene estrias.',2); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Kéfir','K','Es rico en calcio, potasio y vitamina D, que ayuda a fortalecer los huesos. Contiene proteínas y vitamina A, importantes para la salud ocular. Es digerible, regula el sistema digestivo y restablece la flora intestinal. Es un buen probiótico. Es tolerado por quienes no asimilan bien la leche.',15); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Kinoto','K','Pertenece a la familia de los cítricos. Su nombre botánico es Citrus japonica o Fortunella pero se le conoce como quinoto, naranja china o kumquat,es un árbol de crecimiento muy lento lo que lo hace ideal para cultivar en tiestos. Energía 66 kcal 274 kJ Carbohidratos 15.9 g Grasas 0.4 g Proteínas 3.8 g Vitamina C 151 mg (252%) Calcio 266 mg (27%) Hierro 1.7 mg (14%) Fósforo 97 mg (14%) Potasio 995 mg (21%) Sodio 30 mg (2%) % de la cantidad diaria recomendada para adultos.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Kiwi','K','Contiene fibra soluble, por ello ayuda en la digestión y mejora el tránsito intestinal. Es muy digestivo y permite disgregar las proteínas de los alimentos. Rico en antioxidantes, vitamina C. Mejora el sistema inmune. Contiene vitamina E y ácidos grasos que mejoran el estado de las arterias.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Kiwicha','K','Fuente de aminoácidos esenciales como la lisina que ayuda a disminuir los niveles del colesterol. Contiene calcio, fósforo y hierro. Tiene propiedades antiinflamatorias. Además, aporta a la elaboración de enzimas, anticuerpos y hormonas. Incrementa la hemoglobina y la formación de colágeno.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Laurel','L','Contiene sustancias antioxidantes y bactericidas, es rico en vitaminas del grupo B así como minerales como el zinc, el magnesio (equilibra el sistema nervioso, los niveles de azúcar en la sangre y la presión sanguínea), el hierro (necesario para producir las proteínas de la sangre y hemoglobina) y el calcio (importante para fortalecer huesos, dientes y enzimas).',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Lavanda','L','Es antiséptico natural. Tiene propiedades antinflamatorias que te ayudarán a recuperarte de alguna lesión. Relaja el sistema nervioso central, disminuye el estrés, la ansiedad y el insomnio. Es antioxidante, y ayuda a tener una mejor digestión. Es antivírica y antibacteriana.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Leche de avena','L','Esta leche, de tipo vegetal, aporta una gran cantidad de grasas insaturadas como omega 3 y omega 6, ayuda a controlar los niveles de colesterol. Es fuente de minerales como el potasio y en menor medida magnesio y calcio, pero ofrece sustancias hipolipemiantes como los betaglucanos que podrían beneficiar la salud como señala un estudio publicado en Annals of Nutrition & Metabolism.',16); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Leche de coco','L','No contiene lactosa ni glúten. Reduce el riesgo de enfermedades cardiovasculares, ayuda a reducir el colesterol, previene calambres y proporciona energía. Contiene minerales como Potasio, Calcio y Magnesio.',16); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Leche de soya','L','Aporta vitaminas B, D, K y C, además contiene calcio,  hierro, magnesio, fósforo, manganeso y zinc. Contribuye a cuidar al sistema óseo. Favorece el control de los niveles altos de azúcar en sangre.',16); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Leche de almendras','L','No cotiene lactosa ni glúten. Rica en vitaminas E, D y A, proteínas, omega 6, zinc, calcio, hierro, magnesio y potasio, además contiene vitamina B2, el cual, ayuda a que las uñas y el pelo se fortalezcan y que la piel tenga una mejor hidratación.',16); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Lechuga','L','Es un alimento alcalinizante, refrescante y remineralizante. Contiene: agua, celulosa, glúcidos, lípidos y prótidos. Rico en clorofila. Además, es rica en fibra, y por lo tanto ideal para combatir el estreñimiento. Posee propiedades relajantes y favorecedoras del sueño. Tiene poder saciante.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Lentejas','L','Destacan por su alto valor energético al tiempo que son un alimento rico en proteínas. Son ricas en fibra, lo que ayuda a regular el tránsito intestinal y combate el estreñimiento. Son una fuente de hierro y potasio. Contiene ácido fólico y reduce los niveles de azúcar en sangre.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Limón','L','Es antibacteriano por su alto contenido en vitamina C y flavonoides. Aumenta las defensas de tu organismo. Alcaliniza el organismo. Estimula el hígado y ayuda a eliminar toxinas. Protege las células y tejidos del cuerpo. Tiene limoneno, que reduce el riesgo de enfermedades degenerativas.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Llantén','L','Por sus propiedades antibacterianas, el llantén tiene la capacidad de eliminar los microorganismos que causan enfermedades respiratorias. Además, es descongestivo y expectorante. Por lo general, se lo usa para tratar la tos, el asma, la bronquitis, la faringitis y la laringitis.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Lúcuma','L','Energizante natural, brinda fibra, potasio, vitamina B3 y carotenoides. Es rica en niacina. Gracias a esta última estimula el buen funcionamiento del sistema nervioso. Contiene betacaroteno, que tiene propiedades antioxidantes. Previene ciertos cánceres y enfermedades del corazón.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maca','M','Alimento altamente energético. Su perfil nutritivo es similar al de los cereales, con un 60% de carbohidratos, 10% de proteína, 8, 5% de fibra y 2,2% de grasas. Excelente fuente de aminoácidos y abundante en minerales. Contiene vitaminas del grupo B, vitamina C y vitamina E.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maca Amarilla','M','Es un antioxidante que ayuda a retrasar el envejecimiento celular, además reduce síntomas de éstres y fatiga, y actúa como energizante y estimulante natural.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maca Roja','M','Tiene como componentes la vitamina C, el zinc, el hierro y el calcio. Ayuda a combatir casos como de osteoporosis, regeneración ósea, y  de próstata, para disminuir la inflamación.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maca Negra','M','Se caracteriza principalmente por aumentar la resistencia física y sexual, la fertilidad masculina y femenina y la concentración mental, además aumenta la resistencia física y disminuye los efectos del estrés y la fatiga.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maíz (Choclo - Elote)','M','Aporta vitamina B1, B3 y ácido fólico. El maíz tierno conserva la vitamina C y es el único cereal que aporta provitamina A. También proporciona la antioxidante vitamina E. El maíz proporciona abundante fósforo, magnesio y zinc, así como algo de hierro y manganeso.',17); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maíz gigante','M','El maíz es un cereal altamente energético y muy rico en nutrientes digestibles. Aporta proteínas y minerales como calcio, hierro y fósforo, y es una buena fuente de carbohidratos, en su mayoría polisacáridos.',17); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maiz morado','M','En la actualidad, el maíz morado ha adquirido gran importancia debido a su alto contenido de antioxidantes. Es tradicionalmente usado como depurativo, hipotensor, antiinflamatorio y antioxidante.',17); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Malva','M','Contiene principios activos como taninos, mucílagos, malvina y vitaminas A, B1, B2 y C. Esta planta medicinal tiene acción antiinflamatoria, demulcente, antitusiva, laxante, mucolítica, hipoglucemiante, diurética, emoliente y antiséptica. Sus flores son comestibles.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Mandarina','M','La vitamina C en la mandarina ayuda a prevenir resfríos, contribuye a sanar heridas y formar tejido cicatricial, favoreciendo la absorción del hierro. El aceite esencial de la mandarina posee propiedades antimicrobianas. Protege de los virus, hongos e infecciones bacterianas.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Mango','M','Muy rica en vitaminas A y C, minerales, fibras, fitoquímicos y antioxidantes, y aporta baja cantidad de grasa y sodio. Contiene betacaroteno, que previene el asma y ciertos tipos de cánceres. Además, su fibra y potasio reducen el riesgo de enfermedades del corazón. Favorece la digestión.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Manzana','M','Tiene alto contenido en fibras y antioxidantes. Tiene vitaminas del grupo B y C. Ricas en minerales como el fósforo, potasio o calcio. Facilitan la digestión de alimentos ricos en grasas. Cuidan los dientes y las encías. Evitar el estreñimiento. Son diuréticas. Regula la función de los intestinos.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Manzanilla','M','El aceite esencial de la manzanilla tiene propiedades antiinflamatorias, espasmolíticos, digestivo, estimula el flujo sanguíneo y es ligeramente sedante, debido a las cumarinas y flavonoides. Las lactonas sesquiterpénicas son responsables de su actividad aperitiva y digestiva.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Maracuyá','M','Fuente de provitamina A, vitamina C y minerales como potasio, fósforo y magnesio. Es antioxidante y reduce el riesgo de enfermedades como las degenerativas, las cardiovasculares y el cáncer. Es antiinflamatorio. Contiene fibra y reduce el estreñimiento.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Mashua negra','M','Este alimento con proteína, carbohidrato y antocianina es anticancerígeno, y es capaz de tratar el cáncer del colon, piel y próstata. La mashua aporta entre 9 mil y 10 mil unidades de antioxidantes, manteniendo las células jóvenes, aportando también a la desinflamación de los riñones.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Mate','M','A pesar de las afirmaciones de los sitios web de empresas comercializadoras de mate, que afirman que es un «potente» diurético o un potente estimulante o un potente antioxidante, el mate es un ligero estimulante del sistema nervioso, tanto como el café y considerado al mismo nivel, por contener cafeína.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Melocotón (Durazno)','M','Se componen principalmente por agua. Es rico en minerales, potasio, fósforo, magnesio, zinc y selenio. Es rica en fibra y betacaroteno, precursor de la vitamina A, antioxidante y protectora de piel, mucosas y la vista. Facilita la digestión de los alimentos. Es un poderoso reconstituyente.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Melón','M','El 90% de su contenido es agua, por lo que es una de las frutas menos calóricas y con menos azúcares. Por el contrario, es rico es minerales como el potasio y el sodio y vitaminas como la C. El alto grado de agua del melón estimula los riñones para que funcionen con más eficiencia.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Menta','M','Es muy aromática, digestiva, antiinflamatoria y despeja las vías respiratorias. Es rica en vitaminas B1, B2, B3, B5, B6, C y E, betacaroteno, biotina, calcio, magnesio, fósforo y potasio.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Mijo','M','Tiene un alto valor en proteínas, hidratos de carbono y es altamente energético. Contiene hierro, que ayuda aprevenir la anemia. Es un alimento terapéutico puesto que su contenido en vitaminas del grupo B combate problemas de ansiedad y depresión. Rico en fibra y efectos alcalinizantes.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Miso','M','Es un alimento energético. La presencia de ácido linoleico y lecitina que se encuentran en la soja ayudan a regular los niveles de colesterol en sangre. Asimismo, tiene propiedades antioxidantes, por lo que combate el envejecimiento celular. Regula el tránsito intestinal y es depurativo.',18); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Muña','M','Se bebe como infusión y es usada como analgésico, antiespasmódico, antiséptico, contra el reumatismo y para enfermedades respiratorias. Sus propiedades medicinales son atribuidas a su alta capacidad antioxidante. Es fuente de calcio y fósforo, y contribuye al mantenimiento de los huesos.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Nabo','N','Rico en antioxidantes, vitaminas, minerales y tiene un bajo aporte calórico. Su bajo valor calórico hace que los nabos puedan ser incluidos en dietas de control de peso. Los nabos también nos aportan mucha fibra, vitamina A, vitamina C, folatos y hierro. Regulan la función intestinal.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Naranja','N','Rica en vitamina C. La presencia de carotenoides con actividad provitamínica A, protege ante enfermedades cardiovasculares. Sus flavonoides colaboran con las vitaminas en el refuerzo del sistema inmunitario. Contiene ácido cítrico, facilitando la eliminación de residuos tóxicos del organismo.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Naranja roja (Sanguina)','N','Contiene vitamina C, antocianinas y betacarotenos. Reduce los niveles de colesterol y triglicéridos, mejorando la circulación. Además, es rica en ácido fólico y vitamina B1, necesarios para el buen funcionamiento del sistema nervioso y para el desarrollo durante la etapa de crecimiento.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Nectarina','N','Son fuente de minerales como el potasio, el fósforo, el magnesio, el calcio, el sodio, el hierro, el zinc, el yodo y el selenio. También contienen vitaminas C, B6, B3, B2, B1 y carotenos. Protegen ante los radicales libres, retrasan el envejecimiento. Buena para la hipertensión y digestión.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Nuez','N','Contiene ácidos grasos omega 3 mejora enfermedades inflamatorias como la artritis reumatoide y la psoriasis. Tiene vitaminas del grupo B, ácido fólico (B9) y B6, importante para el buen funcionamiento del cerebro y para la producción de glóbulos rojos en sangre. Es fuente vegetal de proteínas.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Nuez de macadamia','N','Contiene ácidos grasos que evitan problemas cerebrovasculares. Reduce problemas de colesterol por su gran aporte de grasas monoinsaturadas. Su contenido en fibra ayuda a regular el tránsito intestinal. Contiene calcio y fósforo que favorece el desarrollo de huesos y dientes.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Oca','O','Es nutricionalmente similar a la papa; aunque tiene casi un 20% menos de calorías por porción y la mitad de sus proteínas, el contenido de carbohidratos y fibra son similares en ambos tubérculos. Rica en vitamina C, ayuda al cuerpo a combatir las infecciones y prevenir enfermedades.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Olluco','O','Aporta muy pocas calorías ya que contiene más de 80% de agua y poco almidón. Contiene calcio, fósforo y vitaminas del complejo B, pero destaca en otras como la vitamina C y el hierro. Muy importante para el desarrollo de los niños, pues posee zinc y eso impulsa su crecimiento.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Orégano','O','Contiene vitaminas A, C E y K, así como fibra, folato, hierro, magnesio, vitamina B6, calcio y potasio. Destacan sus propiedades antioxidantes y antimicrobianas. Bueno para el sistema digestivo. Es antiinflamatorio y bueno para aliviar los resfriados.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Ortiga','O','Altamente nutritivo y energético. Además, contiene abundante fibra que ayuda a combatir el estreñimiento y alivia el tránsito intestinal. Tiene propiedades diuréticas, ayuda a proteger el estómago, la producción de bilis y favorece la digestión. Contiene hierro y ácido fólico.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Papa (Patata)','P','Fuente de energía, aportan vitamina B1, B3 y B6. Ofrecen una cantidad destacada de proteínas y de minerales como selenio, potasio, flúor y hierro. Gracias a su elevado contenido en hidratos de carbono complejos son muy saciantes. Es antioxidante y fortalece el sistema inmune.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Papas nativas','P','Fuente de minerales, donde predomina el potasio, lo que ayuda a reducir la presión arterial en el organismo. Macronutrientes como el hierro y el zinc. Fuente de antioxidantes como los carotenoides y polifenoles, que ayudan a prevenir enfermedades degenerativas. Rica en carbohidratos.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Papaya','P','Alto contenido en vitaminas y minerales, principalmente calcio. Destaca por su contenido en enzimas que favorecen la digestión, desintoxican y disocian la albúmina. Es destacable el efecto cicatrizante de la papaya, por ejemplo, para úlceras gástricas. También es una buena fuente de fibra.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pepino','P','Esta hortaliza aporta vitamina C, y vitaminas del grupo B. Contiene asimismo minerales como el potasio y oligoelementos como el silicio, el molibdeno, el cobre y el manganeso. Refrescante por su alto contenido en agua. Es digestivo, depurativo, diurético, calmante y saludable para el corazón debido a sus esteroles.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pasa','P','Durante la desecación de la fruta fresca, su contenido en agua se reduce, lo que da lugar a la concentración de los nutrientes. El valor calórico de las frutas desecadas es elevado (desde las 163 calorías cada 100 gramos de las uvas secas a las 264 calorías de las uvas pasas) por su abundancia en hidratos de carbono simples.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pera','P','Más del 80% de su peso es agua y prácticamente no contiene grasas, además  es una buena fuente de fibra. Sus pectinas ayudan a reducir el colesterol y su bajo índice glucémico las hace adecuadas para las personas con diabetes. En cuanto a vitaminas, destaca su contenido en vitamina C.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Perejil','P','Es un muy rica en vitamina A, elemento importante para la visión, la piel o el crecimiento de los huesos. Es una muy buena fuente de vitamina C, imprescindible para poder absorber el hierro. Estas propiedades convierten al perejil en un potente antioxidante, un antiinflamatorio y un buen anticoagulante.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pimiento','P','De bajo aporte calórico. Su principal componente es el agua, seguido de las proteínas y  hidratos de carbono. Es una buena fuente de fibra que mejora el tránsito intestinal, además de poseer un efecto saciante.  Todos los pimientos (rojos, verdes y amarillos) son ricos en vitamina C y vitamina A.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Piña','P','Tiene elevado contenido en agua, es poco calórica y contiene bromelina, una enzima que facilita la digestión. Gracias a la bromelina, previene la formación de tumores y el cáncer, especialmente el de estómago. Es una fuente de fibra, de calcio, de magnesio, de potasio y de ácido fólico.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pistacho','P','Es una buena fuente de proteína vegetal, lípidos y también es muy rico en hidratos de carbono. Posee un alto contenido en grasas insaturadas, sobre todo monoinsaturadas, que ayudan a reducir el nivel de colesterol colesterol malo y triglicéridos, así como la tensión arterial.',7); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Pitahaya','P','Es un cactus originario de Baja California (Estados Unidos) y México. También se conoco como Pitaya o Fruta del dragón. Prefiere regiones calurosas y con escasas precipitaciones. Contiene antioxidantes, mucílagos, ácido ascórbico, fenoles. Es rica en Vitamina C, también contiene vitaminas del grupo B, minerales como calcio, fósforo, hierro, y tiene alto contenido en agua y posee proteína vegetal y fibra soluble.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Plátano','P','Destaca por su riqueza en hidratos de carbono, especialmente azúcares cuando este es maduro. Así, se trata de una fuente de energía rápida. Es una buena fuente de fibra que ayuda a combatir el estreñimiento y regula el tránsito intestinal. El plátano es rico en potasio y tiene efectos antioxidantes.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Puerro (Poro)','P','Presenta fibra y algunas vitaminas (básicamente folatos y vitamina C), contiene antioxidantes y hierro, que, es uno de los minerales más presentes en esta verdura. Su porcentaje en fibra es elevado, lo que le confiere un gran efecto saciante. También posee potasio, fósforo y yodo.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Queso vegano','Q','Rico en vitamina E, la provitamina A, y las del complejo B y C. Lleno de fibras y grasas saturadas. Protege la flora intestinal y aportan bacterias probióticas.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Quinoa Roja (Quinua)','Q','Es un pseudocereal cargado de proteínas y ácidos grasos omega 3 y 6. Tiene un perfil más bajo de lípidos (grasas) que la blanca, aunque en general no es un alimento muy graso.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Quinoa Blanca (Quinua)','Q','La quinoa blanca es enormemente nutritiva, ya que contiene proteínas, fibra, fósforo, hierro, potasio y zinc además de vitaminas B, E y ácidos omega 3. Además, contiene dos potentes sustancias bioactivas, la quertecina y el kaempfenol, dos flavonoides que proporcionan efectos antiinflamatorios, antivirales, anticancerígenos y antidepresivos.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Quinoa Negra (Quinua)','Q','Proporciona beneficios nutritivos similares a los de otros tipos de quinua. Es una fuente de proteína completa, que contiene todos los aminoácidos requeridos por el cuerpo. Aparte de esto, contiene vitaminas B, fibra dietética, vitamina E, hierro, fósforo, magnesio y zinc.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Quinoa (Quinua)','Q','Aporta proteínas, ácidos grasos insaturados, minerales (calcio, hierro y magnesio), vitaminas (E, B1, B2 y niacina) y fósforo.  Contiene fibra que ayuda a regular el tránsito intestinal. Bueno para mantener unos huesos sanos y fuertes. Recomendado para mujeres embarazadas y para prevenir la anemia.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Rábano','R','Es una de las hortalizas con más agua, casi un 95%. Destaca en potasio, en vitamina C y en folatos. Es bueno para la artritis y para abrir el apetito. También es un buen diurético que propicia la micción. Tiene propiedades depurativas, digestivas, antibióticas y anticancerígenas.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Remolacha (Beterraga)','R','Agua, proteínas e hidratos de carbono, son los principales elementos que constituyen la remolacha. Contiene fibra y antioxidantes. Previene el estreñimiento, enfermedades cardiovasculares, cáncer y degenerativas. El potasio es el mineral más destacado de la remolacha.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Rocoto','R','Cuenta con propiedades analgésicas y anticancerígenas. Esto se debe a la capsaicina, la misma sustancia que nos provoca irritación en el paladar. Un consumo moderado del rocoto ayuda a mejorar la circulación y prevenir problemas cardiovasculares. Su contenido en fibra regula el tránsito intestinal.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Romero','R','Tiene cualidades antioxidantes y antiinflamatorias, ya que ayuda a regular la circulación de la sangre y oxigena las células. Su consumo ayuda a combatir infecciones bacterianas en el organismo, así como problemas respiratorios y digestivos. Tiene proteínas, fibra, hierro, vitamina A, B1 y una abundante vitamina C.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Rúcula (Arúgula)','R','Tiene una cantidad de vitamina C considerable, carotenos, que son unos potentes antioxidantes y glucosinolatos, que son buenos aliados para la prevención de la aparición de cáncer y tienen potentes propiedades quimioprotectoras. Además, es baja en calorías, ideal en dietas de adelgazamiento. Es depurativa y diurética.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Sacha inchi','S','De propiedades antiinflamatorias, es útil para personas que padecen de artritis, reumatismo y osteoporosis. Es efectivo para el cuidado de la piel y del cabello. Contiene antioxidantes, vitamina A y vitamina E. Un alto índice de omega 3, omega 6 y omega 9. Cuenta con proteínas y aminoácidos esenciales.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Salvia','S','Posee aceite esencial: alfa y beta tuyona, borneol, cineol y alcanfor. De poder expectorante Es un gran recurso en casos de bronquitis, rinitis y procesos similares. También es antifebril, empleada para trastornos gástricos y dolores menstruales.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Sandía','S','Tiene altísimo contenido en agua lo que la convierte en una fruta excelente para calmar la sed. También es una fuente de betacaroteno o provitamina A.  Es antioxidante, antiinflamatoria y analgésica. Contiene poca fibra y sus grasas son ínfimas.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Sauco','S','Contiene flavonoides, vitaminas B1, B2, B5, B6 y C. además de ácido fólico. Minerales como hierro, calcio, magnesio, potasio, fósforo, sodio y zinc. Es antioxidante, depurativo. Ayudan al tratamiento de gripes y resfriados. No contienen grasas y regula la presión arterial.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Semillas de lino','S','Contiene ácido alfalinolénico, el padre de la familia omega 3.  Contiene lignanos, compuestos similares a la fibra, beneficioso para la digestión además es antioxidante. Proporcionan vitamina B1, un nutriente que produce energía. Bueno para el corazón y el sistema nervioso.',5); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Setas shitake','S','Alto en fibra formada por quitina, que ayuda a eliminar las grasas y el colesterol en el intestino, y por betaglucanos como el lentinano. Posee también fructooligosacáridos que benefician el desarrollo de las bacterias intestinales beneficiosas. Destaca su aporte en cobre. Refuerza el sistema inmune.',12); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Soja (Soya)','S','Fuente de proteína vegetal, de vitaminas y de minerales cruciales para reducir el riesgo de sufrir enfermedades crónicas. Contiene los nueve aminoácidos esenciales para el organismo. Además, es alto en fibra, que la hace adecuada para dietas de adelgazamiento. Tiene ácido fólico.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Shiitake','S','Vitaminas B como la B2, B5 y B6. Destaca su aporte de cobre, que refuerza el sistema inmunitario y ayuda a combatir procesos inflamatorios, tumores, virus dañinos, e irónicamente, hongos.',12); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tamarindo','T','Fruto originario de África tropical. Su pulpa es muy nutritiva y calmante de la sed. Tiene buenos niveles de azúcar, pectina, vitamina B y sales minerales. Rico en carbohidratos y valor calórico. Gran protector del hígado y antioxidante. Mantiene bien nuestros huesos, dientes y cabello.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tarwi (Chocho)','T','Contiene ácidos grasos no saturados como el oleico, linoleico y linolenico. De alto contenido en calcio. Contiene más proteínas que la soya. Tiene gran cantidad de proteínas, vitaminas y minerales. Regula el contenido de azúcar en la sangre y ayuda a mantener huesos y dientes sanos.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Té verde','T','Sinónimo de salud y bebida eterna de la juventud por sus antioxidantes y ponifenoles. Mejora nuestro sistema inmune y contiene betaglucano. Reduce altamente el riesgo de contraer cáncer. Estimula el metabolismo y ayuda a perder peso. Fortalece los huesos y aliado contra la diabetes, etc.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tocosh','T','Considerado como la penicilina de los andes por su increíble poder antibiótico. Contiene muchos beneficios como el hierro, vitamina D, C, B6, magnesio y potasio. Previene enfermedades como ulceras, gastritis, problemas respiratorios, caída de cabello, posibles enfermedades a la piel y evitar la osteoporosis.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tilo','T','Es una planta con efectos sedantes. Se emplea para las indigestiones. Sus componentes producen hipotensión. Sus infusiones son diuréticas estimulan el apetito y son antirreumáticas. Se utiliza como cosmético para el cuidado de la piel, radiaciones solares, etc. Evitar su uso en casos específicos.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tofu (Queso de soya)','T','Es el queso de soja, la cual es la legumbre más consumida del mundo. Un excelente sustituto de la carne con mucho menos grasa. Tiene muchas proteínas y el cuerpo las asimila mejor por su combinación de aminoácidos esenciales. Fortalece huesos y ayuda a prevenir menopausia entre otros temas femeninos.',14); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tomate','T','Cuanto más se conoce al tomate, más increíble resulta. Contiene pocas calorías y rica en agua. Destaca por su trio de vitaminas antioxidantes C,E y A y del grupo B más que otras hortalizas. Anticáncer y son mejor cocinados. Se recomienda equilibrar su consumo por algunas leves complicaciones.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Tomillo','T','Es un arbusto con aceites esenciales. Contiene un intenso aroma debido al aceite que contiene timol. Sirve como tonificante, estimulante de apetito, expectorante, antiséptico, atifúngica, etc. Enemigo del catarro, gripe, faringitis y complicaciones clásicas de esta índole. Incluso puede tratarse problemas externos de piel, etc.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Toronja','T','Su pulpa es dulce, amarilla o rosa más o menos oscura. Cuenta con sabor fuerte, entre ácido, amargo y algo dulce. Significativa presencia de vitamina C ayudando al colágeno, huesos, dientes y glóbulos rojos.  Importante para embarazadas y niños. Mejora el impulso nervioso y la actividad muscular.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Toronjil','T','Es hablar de la melisa, una planta medicinal con sabor alimonado. Ayuda a combatir la gastritis por sus aceites esenciales alivia el estrés y es considerado relajante por ende también calma la ansiedad. Tiene un leve efecto estimulante que favorece la concentración y memoria.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Trigo','T','Es fundamental por su poder nutricional. Es muy buen para la dermatitis y otras afecciones de la piel. Esencial para la pituitaria, tiroides y glándulas suprarrenales. Es energético y da vigor en casos de astenia física e intelectual. Contiene gluten y se debe tener un consumo balanceado.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Trigo sarraceno','T','Fuente de proteínas vegetales que se asimilan mejor por la lisina. Rica en vitaminas, destacando el grupo B. Están libres de gluten haciéndolas aptas para celíacos. Tiene aporte elevado de carbohidratos, fibra soluble e insoluble. Combate la diabetes, colesterol e hipertensión.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Trigo tierno','T','El trigo en semilla también puede comerse. Este grano es un alimento muy equilibrado. Elevada cantidad de almidón. Alto en carbohidratos. Aliado de deportistas por sus cantidades energéticas. Uno de los más ricos en proteínas y en fibra. Tiene que estar en remojo previo unas 10 o 12 horas.',8); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Uña de gato','U','Una planta con destacable efectos antiinflamatorios e inmunoestimulantes. Con efectos antihipertensivos por reducir los niveles de calcio intracelular. Se indica en estados virales, inmunodeficiencia e inflamaciones por trastornos intestinales. Combate la irregularidad menstrual y asma.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Uva','U','Son energéticas y abundante en hidratos de carbono. Contiene vitamina C y betacaroteno y cuenta con minerales destacables como el potasio, hierro, etc. No engordan por ser baja en calorías. Puede incluirse en desayunos y cenas para la saciedad hasta 5 veces al día, previa consulta al médico.',1); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Vainilla','V','Es una planta antiséptica, digestiva, ligeramente colerético aromatizante. Se utiliza también como afrodisíaco y emenagogo. Se indica en, diarreas, flatulencias, etc. Hipersensibilidad al aceite esencial de vainilla, al de canela o al bálsamo de Perú. Azúcar vainillado 2 a 8 g por día.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Vainita','V','Ideales en la dieta de control de peso por su bajo aporte calórico y buena fuente de fibra, vitaminas y minerales esenciales. Combate la hipertensión, diabetes, etc. Recomendado en el embarazo para el correcto desarrollo del tubo neural del feto, en especial en las primeras semanas.',6); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Valeriana','V','Hierba medicinal más usada para combatir el insomnio, el nerviosismo y agitación. No genera adicción. Se recomienda en irritabilidad del síndrome premenstrual. En personas con alguna adicción como el cigarro, se suele consumir para la abstinencia. Desaconsejable en el embarazo y lactancia',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Verdolaga','V','Esta planta tiene propiedades laxantes y mejora el tránsito intestinal.  El mucílago es beneficioso por captar sustancias nocivas como grasas, colesterol, etc, sólo si se logra acompañar de abundante agua. En uso tópico se aplica para gingivitis, forúnculos, conjuntivitis y heridas, etc.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Violeta','V','Planta especial para inflamaciones, epilepsia y cefaleas. Combate con eficacia trastornos respiratorios, catarro bronquial, tos ferina, seca y el constipado, etc, por sus propiedades de expectoración y antimicrobianas. Usado en temas de piel. Equilibrar las dosis por su efecto vomitivo.',4); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Yacón','Y','Un tubérculo comestible. Se puede comer cocido o crudo por lo general se usa para jugos. Ayuda a prevenir la diabetes. Favorece la pérdida de peso, anticancerígeno, mejora la densidad ósea, previene la anemia, aumenta la fertilidad masculina, etc. Tiene pequeñas contraindicaciones.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Yuca','Y','Un tubérculo similar a la papa. Gran fuente de vitamina C. Alto en potasio, calcio,etc, además NO contiene gluten. Rebaja los niveles de colesterol y triglicéridos. La yuca no debe comerse cruda pues sería tóxica. Se ha utilizado el agua de maceración para combatir la caspa o caída de pelo.',11); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Zanahoria','Z','La hortaliza con más betacaroteno, lo cual lo hace una aliada indiscutible de la vista, la piel y mucosas. Pero también cuenta con vitamina C y E, de efecto antioxidante. Su calcio es muy asimilable por el organismo. Su zumo o pulpa actúa como bálsamo contra el acné, quemaduras, etc.',3); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Zapallo','Z','Cuenta con innumerables propiedades como regular la función intestinal por ser alta en fibra y producir sensación de saciedad. Regula el sistema nervioso y es gran fortalecedor óseo. Gran desintoxicante y la regularidad de su consumo mejora el funcionamiento de la vejiga y riñones, etc.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Zapallito Italiano','Z','También conocida como calabacín. Ayuda a bajar el nivel de colesterol y contribuye a disminuir el riesgo de la aterosclerosis. Fortalece la vista, gracias a la luteína y la zeaxantina.',10); 
insert into aliment(aliment_name,letter,description,aliment_category_id)values('Zarzamora','Z','Es una planta generalmente silvestre de la que se aprovechan sus frutos, unas bayas pequeñas de color negro muy aromáticas y algo ácidas. Se consumen crudas, aunque también se emplean en la elaboración de compotas, macedonias, tartas, etc. Son ricas en vitaminas y minerales. Además aportan fibra y contienen pocas calorías.',10); 



delete from status where status_type_id = 5;
delete from status where status_type_id = 6;
delete from status_type where status_type_id = 5;
delete from status_type where status_type_id = 6;



insert into status_type(status_type_id, name)values(5, 'product');
insert into status(status_id, status_type_id,status_code, name)values(6, 5,'ACTIVE_PD', 'active'), (7, 5,'INACTIVE_PD', 'inactive');



insert into status_type(status_type_id, name)values(6, 'payment');
insert into status(status_type_id, status_id, status_code, name)values
(6, 8, 'PENDING',   'Pago creado, esperando confirmación'),
(6, 9, 'PAID',      'Pago confirmado exitosamente'),
(6, 10, 'FAILED',    'Pago rechazado o fallido'),
(6, 11, 'CANCELLED', 'Pago cancelado por el usuario'),
(6, 12, 'EXPIRED',   'Sesión de pago expirada'),
(6, 13, 'REFUNDED',  'Pago reintegrado'),
(6, 14, 'ERROR_GENERATE_URL',  'Error durante la generación de URL de pago');



INSERT INTO product(product_id, product_code, product_name,
	price, product_description)
values(1, 'QALERT-0001', 'QALERT PREMIUM', 100, 'versión premium del app'),
    (2, 'QALERT-0002', 'QALERT PREMIUM 2', 600, 'versión premium del app 2'),
    (3, 'QALERT-0003', 'QALERT PREMIUM 3', 1200, 'versión premium del app 3');



INSERT INTO subscription
(`subscription_id`,
`product_id`,
`discount`,
`subscription_months`,
`created_datetime`,
`subscription_status`)
VALUES
(4, 1, 10, 1, now(), 1),
(5, 2, 20, 6, now(), 1),
(6, 3, 30, 12, now(), 1);



INSERT INTO currency (currency_id, currency_code, currency_name, symbol) VALUES
(1, 'USD', 'SOL', 'S/');