use qalert_bd;

update master set value_varchar = 
'TÉRMINOS Y CONDICIONES
Estos Términos y Condiciones (en adelante, "Términos") regulan el acceso y uso de los servicios proporcionados por Q’Alert. (en adelante, "la Empresa", "nosotros", "nuestro") a través de su sitio web https://qalert.life/terminos-y-condiciones/  y la aplicación móvil asociada (en adelante, "el Servicio"). Al acceder o utilizar el Servicio, usted (en adelante, "el Usuario", "usted") acepta cumplir con estos Términos. Si no está de acuerdo con estos Términos, no utilice el Servicio.
Este App es propiedad y operada por SQCORP S.A.C., los presentes Términos y condiciones rigen el uso que toda persona (futuro usuario) hace de la Plataforma y de cualquier Servicio que sea de propiedad o esté bajo el dominio de Q’Alert. Este documento contiene información legal que el usuario está condicionado a leer en su totalidad, asimismo, la Política de Privacidad de Datos. Una vez aprobado los presentes Términos y Condiciones y la Política de Privacidad de Datos, se entiende que el Usuario los ha leído y aceptado, y entiende que estos le son legalmente vinculantes y obligatorios. Por tanto, acepta las condiciones de utilización y aprovechamiento de la Plataforma en general. Al utilizar esta plataforma, el usuario acepta la recolección, almacenamiento y uso de sus datos conforme a lo establecido en nuestra Política de Privacidad. En caso contrario, el Usuario deberá abstenerse a hacer uso de la Plataforma bajo cualquier concepto, ya sea directa o indirectamente.

1. DEFINICIONES A TENER EN CUENTA
Propiedad Intelectual y Uso de la Plataforma. Todos los contenidos, características y funcionalidades del Servicio, incluyendo, pero no limitado a textos, gráficos, logotipos, íconos, imágenes y software, son propiedad de la Empresa o de sus licenciantes y están protegidos por leyes de derechos de autor y propiedad intelectual. El uso no autorizado de cualquier contenido puede constituir una violación de estas leyes. Todo el contenido disponible en esta plataforma, incluyendo, pero no limitado a software, gráficos, logos, y marcas registradas, es propiedad exclusiva de SQCORP o sus licenciantes. El uso de la plataforma no implica la concesión de ningún derecho o licencia sobre el contenido mencionado.
Los siguientes términos tienen el significado que se les asigne expresamente en estos Términos de Uso o en la Política de Privacidad a continuación: 
Todo tipo de información: ya sea gráfica o escrita, imágenes, audio y video, incluyendo pero no limitándose a la ubicación, anuncios, comentarios, noticias, datos, guiones, gráficos, dibujos o imágenes, textos, diseño, esquemas, mapas y características interactivas presentadas por Q’Alert en la Plataforma (y cualquier software y códigos informáticos subyacentes), así como también programas o algoritmos computacionales, módulos de programación, manuales de operación, sea que dicho Contenido es generado, provisto o de cualquier otra forma producido o suministrado por Q’Alert, los Usuarios o terceros. 
Equipo: significa los teléfonos móviles y smartphones, tablets, computadores y cualquier otro aparato electrónico por el cual se pueda acceder a la Plataforma. 
Material de Usuarios: significa toda clase de fotografías, videos, comentarios, comunicaciones que hayan sido subidos o cargados por los Usuarios a la Plataforma. 
Perfil: significa la cuenta personal creada por cada Usuario que acredita el registro en el Aplicativo, de acuerdo con la información personal provista por el mismo a Q’Alert, la cual incluye su nombre, apellidos, fecha de nacimiento, sexo, dirección, teléfono, nombre de usuario, correo electrónico y contraseña. 
Plataforma: significa el sitio web, aplicaciones móviles y plataforma operada por Q’Alert, por los cuales los Usuarios podrán acceder a los Servicios. 
Política de Privacidad: significa las políticas de privacidad de Q’Alert, las cuales se encuentran debidamente publicadas en la Plataforma. 
Producto(s): significa alimentos, bebidas alcohólicas y no alcohólicas y otros artículos que la plataforma tiene en su base de datos. 
Servicios: significa todos los servicios ofrecidos por medio de la plataforma, a los cuales los Usuarios pueden acceder, por medio de la Plataforma y sus Equipos. 
Términos y condiciones, Términos de Uso: significa los presentes Términos y Condiciones de Q’Alert. 
Usuario(s): significa toda persona que utilice (navegue) o que se encuentra registrado como tal en la Plataforma, de acuerdo con lo señalado en los presentes Términos y Condiciones.

2. ACEPTACIÓN DE LOS TÉRMINOS DE USO
Al utilizar el Servicio, usted acepta estos Términos y cualquier modificación futura. La Empresa se reserva el derecho de modificar estos Términos en cualquier momento. Las modificaciones serán efectivas inmediatamente después de su publicación en el Servicio. Su uso continuado del Servicio tras la publicación de cambios constituye su aceptación de dichos cambios. Mediante la creación de un perfil y/o la utilización en cualquier forma de la Plataforma, el Usuario acepta todos los Términos de Uso aquí mencionados y la Política de Privacidad. 
El Usuario se compromete a utilizar el Servicio de manera legal y conforme a estos Términos. Está prohibido:
•	Utilizar el Servicio para actividades ilegales o no autorizadas.
•	Interferir con el funcionamiento del Servicio o intentar acceder a sistemas o redes relacionados.
•	Compartir información falsa o engañosa.
Sin perjuicio de lo anterior, algunas funciones que se ofrecen en la Plataforma pueden estar sujetos a términos y condiciones adicionales. En ese caso, el uso que el Usuario haga de dichos servicios estará sujeto, además, a los referidos términos y condiciones adicionales, que se incorporan a los presentes Términos de Uso por medio de esta referencia. En caso de que el Usuario no los acepte, deberá abstenerse de utilizar en cualquier forma dichos servicios.

3. SOBRE Q’ALERT
Q’Alert es una aplicación de alerta alimentaria que puede ayudar a mejorar la calidad de vida de las personas a través del escaneo de los ingredientes que figuran en los empaques de los alimentos de consumo masivo para poder realizar un consumo o alimentación responsable.

4. USO DE MATERIALES
Salvo que se disponga lo contrario, todos los derechos sobre el contenido son de propiedad de Q’Alert. Se concede al usuario una licencia limitada, no exclusiva y no transferible para acceder y utilizar la plataforma de conformidad con estos términos. Está prohibido realizar ingeniería inversa, modificar, distribuir, o crear obras derivadas del software o cualquier parte de la plataforma sin la autorización expresa de Q’Alert. Los Usuarios se encuentran autorizados para utilizar la Plataforma, así como para descargar material exhibido en ella, pero únicamente para uso personal, estando expresamente prohibido su copia, reproducción, publicación, descarga, codificación, modificación, traducción, interpretación, exhibición, distribución, transmisión o difusión en medios de comunicación, sin la autorización previa, expresa y por escrito de Q’Alert. Los derechos de autor y otros derechos de propiedad sobre el contenido, con independencia de su descarga por parte de los Usuarios, son de propiedad de Q’Alert, haciendo expresa reserva del ejercicio de todas las acciones tanto civiles como penales destinados al resguardo de sus legítimos derechos de propiedad intelectual e industrial.

5. CUENTA DE USUARIO
Para acceder a ciertas funciones del Servicio, el Usuario puede necesitar crear una cuenta. El Usuario es responsable de mantener la confidencialidad de su contraseña y de todas las actividades realizadas bajo su cuenta. Debe notificar a la Empresa inmediatamente sobre cualquier uso no autorizado de su cuenta. Se podrá crear una sola cuenta por persona y la persona que crea un Usuario es la única persona autorizada para el acceso a la plataforma por intermedio de dicho Usuario. El Usuario es responsable de mantener la confidencialidad de cualquier contraseña o número de cuenta proporcionado por el Usuario o Q’Alert para acceder a la Plataforma. Cada Usuario es el único y absoluto responsable de todas las actividades que ocurran bajo su contraseña o cuenta. Q’Alert no tiene control sobre el uso de la cuenta de un Usuario y renuncia expresamente a cualquier responsabilidad derivada de la misma. En caso de que un Usuario sospeche que un tercero pudiera estar accediendo a la plataforma bajo su cuenta de Usuario o utilizando su contraseña, notificará a Q’Alert inmediatamente. El usuario tiene que ser mayor de 18 años para poder hacer uso de la aplicación y en caso se registre con una cuenta falsa o se detecte que es falsa la cuenta se bloqueará y no podrá hacer uso por tiempo indefinido del aplicativo.

6. Q’ALERT PREMIUM
Q’ALERT PREMIUM es un servicio de suscripción opcional que ofrece todas las funciones de lector de productos desbloqueados (aditivos rojos, amarillos y verdes), guía natural, creación de más de 2 perfiles y promociones exclusivas a sus miembros. El costo de la suscripción se encuentra publicado dentro de la aplicación de Q’Alert. El precio está sujeto a cambios, pero este se respeta durante el periodo de vigencia de cada suscripción y no se aplicará hasta que expire su membresía actual y sea renovada por un nuevo periodo. Los términos y condiciones de uso de Q’Alert y Q’Alert Premium pueden modificarse de vez en cuando, y puedes consultarlos en todo momento en esta página, ya que se mantendrá actualizado. Los cambios, excepto los de precio, se aplicarán tanto a membresías nuevas como a membresías vigentes. La renovación de la suscripción se realiza de manera automática, pero siempre tendrás la opción de cambiar esta configuración entrando al menú “Cuenta”, opción “Premium”. Los clientes Q’Alert Premium pueden dar de baja su suscripción (anual, semestral, mensual) en cualquier momento y lo pueden hacer enviando un mail a soporte@qalert.life. Con respecto a la devolución de dinero, durante los primeros 30 días se devolverá el 100% del costo de la membresía (esto única y exclusivamente la primera vez que se descargue). Los siguientes 6 primeros meses, se devolverá el 85% del proporcional a los meses restantes de la membresía. A partir del séptimo mes de uso, no se harán devoluciones sobre el monto pagado por la membresía anual.

Q’Alert se reserva el derecho de cancelar tu suscripción a Q’Alert Premium, sin aviso y a discreción de Q’Alert. Si Q’Alert cancelara tu suscripción, automáticamente se procesaría una devolución por el monto equivalente al porcentaje de días que quedan de tu suscripción multiplicado por el valor que pagaste por tu membresía.

8. RENUNCIA
El uso de Q’Alert es bajo el propio riesgo del Usuario. En ningún caso Q-Alert será responsable por cualquier daño directo, indirecto, incidental, especial o consecuente que surja del uso o la imposibilidad de uso de la plataforma, incluyendo, sin limitación, errores técnicos o interrupciones en el servicio. Los Servicios se prestan tal como son ofrecidos, sin garantías de ningún tipo, explícita o implícita. Q’Alert no efectúa ninguna clase de representación o garantía relativa a la exactitud o totalidad del contenido ofrecido a través del uso de Q’Alert sobre el contenido de cualquier sitio web vinculado al uso de Q’Alert. Q’Alert no garantiza que la Plataforma funcionará libre de errores o que esté libre de virus u otros productos peligrosos. Si el uso de la Plataforma deriva en la necesidad de servicio técnico o reemplazo de equipo o datos, Q’Alert no será responsable de dichos costos. Q’Alert, en la medida máxima permitida por la ley, no violación de derechos de terceros y la garantía de idoneidad para un propósito particular. Q’Alert no garantiza, en ninguna circunstancia, la exactitud, confiabilidad, exhaustividad y actualidad de los contenidos, servicios, soporte, software, textos, gráficos o vínculos. Q’Alert y sus filiales y proveedores de licencias no garantiza, en ninguna circunstancia, que la información personal suministrada por el Usuario pueda ser objeto de apropiación indebida, interceptada, borrada, destruida o usada por terceros.

9. REPORTES Y DENUNCIAS
Los Usuarios podrán reportar a Q’Alert cualquier conducta o contenido que pueda infringir estos Términos de Uso, la Política de Privacidad o la legislación aplicable. Para tal efecto, la Plataforma contará con una función llamada Q’Box donde podrán poner sus sugerencias. Recibida una sugerencia, Q’Alert, a su entera discreción, determinará si corresponde la eliminación o modificación del Contenido.

10. LIMITACIÓN DE RESPONSABILIDAD
El Usuario acepta que Q’Alert no se hace responsable por ningún daño directo, indirecto, lucro cesante, daño emergente, daño incidental, especial o consecuencial, proveniente de o en relación con (i) el uso de la Plataforma por parte del Usuario o de otros Usuarios; (ii) el rendimiento o navegación en la Plataforma o sus enlaces a otros sitios web; (iii) la seguridad del uso de los Productos adquiridos en referencia a la información que brindamos. Además, el Usuario acepta que QAlert no se hace responsable de los daños derivados de la interrupción, suspensión o terminación de los Servicios, incluyendo sin limitación daño directo, indirecto, lucro cesante, daño emergente, daño incidental, especial o consecuencial, cuando dicha interrupción, suspensión o terminación estuviera justificada o causada por un tercero. En la máxima medida permitida por la ley, la Empresa no será responsable de ningún daño indirecto, incidental, especial o consecuente que surja de o esté relacionado con el uso del Servicio. Esto incluye, pero no se limita a, pérdidas de ganancias, datos o uso, incluso si se ha advertido sobre la posibilidad de tales daños.

11. INDEMNIDAD
El Usuario se obliga a defender, indemnizar y mantener indemne a Q’Alert, sus funcionarios, directores, agentes y afiliados, frente a cualquier reclamo, acción, costo, daños, sanción, multa y gasto, incluyendo sin limitación honorarios de abogados, que surjan de del uso no autorizado de la Plataforma por parte del Usuario o de cualquier incumplimiento de estos Términos y Condiciones, incluyendo sin limitación, cualquier violación de cualquier ley, ordenanza, orden administrativa, norma o reglamento. Q’Alert dará aviso, a la brevedad, de cualquier reclamación, demanda o procedimiento, y tendrá derecho a asumir la defensa respecto de cualquier reclamación, demanda o procedimiento. El Usuario acepta indemnizar y mantener indemne a la Empresa, sus afiliados, directores, empleados y agentes de cualquier reclamo, pérdida, responsabilidad, daño, costo o gasto (incluidos honorarios razonables de abogados) que surjan de su uso del Servicio o de su violación de estos Términos.

12. TERMINACIÓN
Q’Alert puede modificar o interrumpir la Plataforma, o puede modificar, suspender o interrumpir su acceso o el soporte, con o sin previo aviso v sin ninguna responsabilidad frente a los Usuarios o cualquier tercero. Q’Alert se reserva el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en la plataforma. El uso continuo de la plataforma después de la modificación se considerará como aceptación de los nuevos términos. Aun cuando un Usuario pierda el derecho a utilizar la Plataforma, los presentes Términos y Condiciones serán ejecutables en su contra. Q’Alert se reserva el derecho de suspender o terminar el acceso a la plataforma de cualquier usuario que incumpla estos términos o haga un uso indebido de la misma, con o sin previo aviso. El Usuario podrá terminar estos Términos y Condiciones en cualquier momento, dejando de utilizar la Plataforma. La terminación de los Servicios y/o el cierre de la cuenta del Usuario, por cualquier motivo, no generará compensación en su favor por parte de Q’Alert. 

13. RESOLUCIÓN DE CONFLICTOS
Cualquier dificultad o controversia que se produzca entre la plataforma o alguna empresa afiliada a nuestra plataforma, será sometida a la competencia y jurisdicción de los Jueces y Tribunales del Distrito Judicial de Lima.

14. LEY APLICABLE Y DIVISIBILIDAD
Estos Términos y Condiciones estarán regidos e interpretados de acuerdo con las leyes de la República del Perú. Los Términos de Uso y la Política de Privacidad constituyen el acuerdo completo entre el Usuario y Q’Alert con respecto a los Servicios, uso de la Plataforma y del contenido, y sustituyen todas las comunicaciones y propuestas previas o contemporáneas (ya sean escritas, orales o electrónicas) entre el Usuario y Q’Alert con respecto a la Plataforma y a los Servicios. Cualquier disputa que surja en relación con estos Términos o del uso de esta plataforma será sometida y se resolverá exclusivamente en la jurisdicción exclusiva de los tribunales de Lima, Perú y se regirá por las leyes de Perú.

15. DESCUENTOS, PROMOCIONES Y BENEFICIOS DE LAS TIENDAS
Q’Alert no aplica los descuentos y promociones que se muestran en tiendas. Sin embargo, tendremos promociones con diferentes marcas afiliadas. Q’Alert tampoco aplica los beneficios de la compra como acumulación de puntos, uso de tarjetas de cliente frecuente, redondeos o similares.

16. MODIFICACIONES
Q’Alert podrá, a su sola y absoluta discreción, cambiar por sí y sin aviso previo estos Términos y Condiciones. Sin embargo, tales cambios sólo se aplicarán desde el momento en que sean publicados en la Plataforma y regirán para las transacciones que se celebren con posterioridad a su entrada en vigor.

17. VARIOS
Si alguna disposición de estos Términos se considera inválida o inaplicable, las disposiciones restantes seguirán en pleno vigor y efecto. Estos Términos constituyen el acuerdo completo entre el Usuario y la Empresa respecto al uso del Servicio y reemplazan cualquier acuerdo previo.
Estos Términos de Uso son personales, y no se pueden ceder, transferir ni sublicenciar, excepto con el consentimiento previo por escrito de Q’Alert. Q’Alert podrá ceder, transferir o delegar cualquiera de sus derechos y obligaciones en virtud de estos Términos de Uso sin el consentimiento del Usuario. A menos que se especifique lo contrario en estos Términos de Uso, todos los avisos o modificaciones serán considerados debidamente entregados desde el momento de su publicación en la Plataforma, o bien desde el momento en que sea notificado al Usuario, según corresponda.

18. CONTACTO
Si el Usuario tiene alguna duda respecto de los Términos y Condiciones, Política de Privacidad, uso de la Plataforma o de su Perfil, podrá ponerse en contacto con Q’Alert vía el correo electrónico qalertlife@gmail.com. Los mensajes serán atendidos a la mayor brevedad posible.

19. MÉTODO DE PAGO
El pago de los Servicios se realizará a través del método de pago ingresado y elegido por el Usuario en la Plataforma, conforme a los términos y condiciones existentes entre el Usuario y la institución financiera, emisor de la tarjeta de crédito o débito del método de pago elegido. Si se determina que su método de pago principal está vencido, no es válido o no se puede cobrar de otra manera, el Usuario acepta que Q’Alert puede cobrar todos los cargos y precios aplicables para los servicios a cualquier otra tarjeta o método de pago disponible guardado o vinculado a su cuenta.
'
where table_id = 1 and field_id = 1