server.port=8081
app.name=Q'ALERT

spring.application.name=qalert-services
service.context=/qalert-services

#IZIPAY
izipay.base-url=https://api.micuentaweb.pe
izipay.api-createPayment=/api-payment/V4/Charge/CreatePaymentOrder
izipay.api-getPayment=/api-payment/V4/Charge/PaymentOrder/Get
# izipay.api-user=89289758
# izipay.api-password=testpassword_7vAtvN49E8Ad6e6ihMqIOvOHC6QV5YKmIXgxisMm0V7Eq
# usuario de qalert, el otro es de izipay
izipay.api-user=86259949
izipay.api-password=testpassword_78gm1mZvlRLma6NPUUHhrhBv1ymiFTsA2kxsQ9DgKlxAu

#POOL CONEXIONES
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=MyHikariCP

#ACCESO BD nube
# spring.datasource.hikari.jdbc-url=jdbc:mysql://qalter-db.c23oksyeeje8.us-east-1.rds.amazonaws.com:3306
 spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/qalert_bd_1
 spring.datasource.hikari.schema=qalert_bd_1
 spring.datasource.hikari.username=qalert_app
 spring.datasource.hikari.password=admin10$$Admin10
 spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver


# qalert_bd_test3  qalert_bd_user1
aws.textextrac.access-key=AKIAWOFLUTRIWZ++++++64J6XY
aws.textextrac.secret-key=bxq9OM/9vVTNqr15zihh++++++DV8Yix1Jke+CuumwAd45


#MULTIPART FILE
spring.servlet.multipart.max-file-size=10MB

#Google email
google.email.contrasenia=lxnxptvdfkzszqte
google.email.remitente=qalertlife@gmail.com

#Log
logging.file.path=publico/log
logging.file.name=publico/log/log.txt
logging.level.root=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:MM:ss.SSS} | %c.%M %m%n
logging.pattern.file=%d{yyyy-MM-dd HH:MM:ss.SSS} | %c.%M %m%n